rendering
sampleInputText
	^ '<table style="width:100%">
	<thead>
  <tr>
    <th>Column 1</th>
    <th><em>Column 2</em></th>
    <th>Column 3</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td> <img src="http://seaside.st/styles/logo-plain.png" alt="Seaside logo" </td>
    <td colspan="2" rowspan="2"><ul style="list-style-type:square">
  <li>Coffee</li>
  <li>Tea</li>
  <li>Milk</li>
</ul> 
</td>
  </tr>
  <tr>
    <td><a href="http://seaside.st" target="_blank">Visit Seaside website!</a></td>
  </tr>
</tbody>
</table>'
